[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/realSunyz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/realSunyz"

[social.params]
icon = "brand-twitter"

[[main]]
name = "首页"
pageRef = "/"
weight = 10

[[main.params]]
icon = "home"

[[main]]
name = "归档"
pageRef = "/archives"
weight = 20

[[main.params]]
icon = "archives"

[[main]]
name = "友链"
pageRef = "/"
weight = 30

[[main.params]]
icon = "link"

[[main]]
name = "关于"
pageRef = "/about"
weight = 40

[[main.params]]
icon = "user"

